name: "Job to merge pull request"
on:
  pull_request:
    types:
      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
       - name: automerge
         uses: "pascalgn/automerge-action@v0.16.4"
         env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""